###############################################################################
### ==> Normal
###############################################################################

- alias: Wohnzimmermodus auf Normal setzen, wenn das Wohnzimmer eingeschaltet wird
  trigger:
    - platform: state
      entity_id: input_select.state_living_room
      to: 'An'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.mode_living_room
        option: 'Normal'

- alias: Wohnzimmermodus mit Remote auf Normal setzen
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: tradfri_switch_wohnzimmer_1
        event: 2002
    - platform: event
      event_type: deconz_event
      event_data:
        id: tradfri_switch_wohnzimmer_2
        event: 2002
  condition:
    - condition: state
      entity_id: input_select.mode_living_room
      state: 'Gedaemmt'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.mode_living_room
        option: 'Normal'

###############################################################################
### ==> Gedaemmt
###############################################################################

- alias: Wohnzimmermodus mit Remote auf Gedaemmt setzen
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: tradfri_switch_wohnzimmer_1
        event: 3002
    - platform: event
      event_type: deconz_event
      event_data:
        id: tradfri_switch_wohnzimmer_2
        event: 3002
  condition:
    - condition: state
      entity_id: input_select.mode_living_room
      state: 'Normal'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.mode_living_room
        option: 'Gedaemmt'