- platform: workday
  name: workday_today
  country: DE
  province: RP

- platform: workday
  name: workday_tomorrow
  days_offset: 1
  country: DE
  province: RP

- platform: template
  sensors:
    occupancy_kitchen:
      friendly_name: "Anwesenheit Küche"
      value_template: >-
        {{ is_state('binary_sensor.motion_kitchen_1', 'on')
        or is_state('binary_sensor.motion_kitchen_2', 'on')
        or is_state('binary_sensor.motion_kitchen_3', 'on') }}
    occupancy_dining_room:
      friendly_name: "Anwesenheit Esszimmer"
      value_template: >-
        {{ is_state('binary_sensor.motion_dining_room_1', 'on')
        or is_state('binary_sensor.motion_dining_room_2', 'on') }}
    occupancy_living_room:
      friendly_name: "Anwesenheit Wohnzimmer"
      value_template: >-
        {{ is_state('binary_sensor.motion_living_room_1', 'on')
        or is_state('binary_sensor.motion_living_room_2', 'on') }}
    occupancy_study:
      friendly_name: "Anwesenheit Büro"
      value_template: >-
        {{ is_state('binary_sensor.motion_study_1', 'on') }}

- platform: ping
  host: 192.168.178.80
  name: ping_pc_pascal
  scan_interval: 10
  count: 1
