group:
  bewohner:
    name: Bewohner
    entities:
        - person.andrea
        - person.pascal
  all_thermostats:
    name: Alle Thermostate
    entities:
       - climate.badezimmer_1
       - climate.thermostat_living_room_1
       - climate.thermostat_living_room_2
       - climate.thermostat_study_1
  thermostats_house_state:
    name: Thermostate mit Hauszustand
    entities:
       - climate.badezimmer_1
       - climate.thermostat_living_room_1
       - climate.thermostat_living_room_2
  thermostats_living_room:
    name: Thermostate Wohnzimmer
    entities:
       - climate.thermostat_living_room_1
       - climate.thermostat_living_room_2
  all_sonos:
    name: Alle Sonos-Geräte
    entities:
      - media_player.esszimmer
      - media_player.kueche
      - media_player.beam
  all_doors:
    name: Alle Türen
    entities:
      - binary_sensor.living_room_balcony_door
      - binary_sensor.office_balcony_door

light:
- platform: group
  name: Wohnzimmer Ventilator
  entities:
    - light.wohnzimmer_ventilator_1
    - light.wohnzimmer_ventilator_2
- platform: group
  name: Front Hallway Main
  entities:
    - light.front_hallway_main_1
    - light.front_hallway_main_2
- platform: hyperion
  name: Hyperion Wohnzimmer
  host: 192.168.178.151

cover:
  - platform: group
    name: Study Door
    entities:
      - cover.study_door_1
      - cover.study_door_2

webostv:
  host: !secret ip_adress_tv_living_room
  name: Fernseher Wohnzimmer
  turn_on_action:
    service: wake_on_lan.send_magic_packet
    data:
      mac: !secret mac_adress_tv
  customize:
    sources:
      - livetv
      - youtube
      - netflix
      - amazon
      - xbox
      - playstation
      - switch

media_player:

notify:
  - name: telegram_pascal
    platform: telegram
    chat_id: !secret telegram_chat_id_pascal
  - name: telegram_andrea
    platform: telegram
    chat_id: !secret telegram_chat_id_andrea
  - name: telegram_alle
    platform: group
    services:
      - service: telegram_pascal
      - service: telegram_andrea

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - !secret telegram_chat_id_pascal
      - !secret telegram_chat_id_andrea

wake_on_lan:

http:
  server_port: 80

switch:
  - platform: rest
    name: WLED TV Backlighting LOR
    resource: http://192.168.178.150/json/state
    body_on: '{"lor": 0}'
    body_off: '{"lor": 1}'
    is_on_template: '{{value_json.lor == 0}}'
    headers:
      Content-Type: application/json

tts:
  - platform: google_translate
    language: 'de'

history:
  exclude:
    domains:
      - automation
      - scene
      - zone

logbook:
  exclude:
    entities:
      - input_number.global_hue_primary
      - input_number.global_hue_secondary
      - input_number.global_hue_tertiary

default_config:

homeassistant:
  customize: !include customize.yaml
  latitude: !secret zone_home_lat
  longitude: !secret zone_home_lon
  unit_system: metric
  time_zone: Europe/Berlin
  name: Yggdrasil

# INCLUDES
zone: !include zones.yaml
input_select: !include input_select.yaml
input_boolean: !include input_boolean.yaml
input_number: !include input_number.yaml
scene: !include scenes.yaml
automation: !include_dir_merge_list automations/
binary_sensor: !include binary_sensor.yaml
script: !include_dir_merge_named scripts/
sensor: !include_dir_merge_list sensors/
frontend:
  themes: !include_dir_merge_named themes