device_tracker:
  - platform: fritz
    host: !secret hostname_fritz_box
    new_device_defaults:
      track_new_devices: false

group:
  bewohner:
    name: Bewohner
    entities:
        - person.andrea
        - person.pascal
  all_thermostats:
    name: Alle Thermostate
    entities:
       - climate.badezimmer_1
       - climate.thermostat_living_room_1
       - climate.thermostat_living_room_2
  thermostats_living_room:
    name: Thermostate Wohnzimmer
    entities:
       - climate.thermostat_living_room_1
       - climate.thermostat_living_room_2

light:
- platform: group
  name: Wohnzimmer Ventilator
  entities:
    - light.wohnzimmer_ventilator_1
    - light.wohnzimmer_ventilator_2

webostv:
  host: !secret ip_adress_tv_living_room
  name: Fernseher Wohnzimmer
  turn_on_action:
    service: wake_on_lan.send_magic_packet
    data:
      mac: !secret mac_adress_tv
  customize:
    sources:
      - livetv
      - youtube
      - netflix
      - amazon
      - xbox
      - playstation
      - switch

media_player:

notify:
  - name: telegram_pascal
    platform: telegram
    chat_id: !secret telegram_chat_id_pascal
  - name: telegram_andrea
    platform: telegram
    chat_id: !secret telegram_chat_id_andrea
  - name: telegram_alle
    platform: group
    services:
      - service: telegram_pascal
      - service: telegram_andrea

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - !secret telegram_chat_id_pascal
      - !secret telegram_chat_id_andrea

wake_on_lan:

http:
  server_port: 80

speedtestdotnet:

switch:
  - platform: flux
    disable_brightness_adjust: true
    lights:
      - light.kueche_decke

history:
  exclude:
    domains:
      - automation
      - scene
      - zone

logbook:
  exclude:
    entities:
      - input_number.global_hue_primary
      - input_number.global_hue_secondary
      - input_number.global_hue_tertiary

default_config:

homeassistant:
  customize: !include customize.yaml
  latitude: !secret zone_home_lat
  longitude: !secret zone_home_lon
  unit_system: metric
  time_zone: Europe/Berlin
  name: Yggdrasil

# INCLUDES
zone: !include zones.yaml
input_select: !include input_select.yaml
input_boolean: !include input_boolean.yaml
input_number: !include input_number.yaml
scene: !include scenes.yaml
automation: !include_dir_merge_list automations/
binary_sensor: !include binary_sensor.yaml
script: !include_dir_merge_named scripts/
sensor: !include_dir_merge_list sensors/
frontend:
  themes: !include_dir_merge_named themes