- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /
    - type: memory_use_percent
    - type: processor_use

- platform: gitlab_ci
  gitlab_id: !secret gitlab_id
  token: !secret gitlab_token
  scan_interval: 30

- platform: template
  sensors:
    thermostat_bathroom_1_battery_level:
      friendly_name: "Batterie Thermostat Badezimmer"
      unit_of_measurement: '%'
      device_class: 'battery'
      value_template: "{{ state_attr('climate.badezimmer_1', 'battery_level') }}"

    ha_counter_lights:
      friendly_name: "Lichter"
      value_template: "{{ states.light | count}}"

    ha_counter_automations:
      friendly_name: "Automatisierungen"
      value_template: "{{ states.automation | count }}"

    ha_counter_sensors:
      friendly_name: "Sensoren"
      value_template: "{{ states.sensor | count + states.binary_sensor | count}}"

    ha_counter_switches:
      friendly_name: "Schalter"
      value_template: "{{ states.switch | count}}"