###############################################################################
### ==> Bewohnt
###############################################################################

- alias: Haus werktags morgens einschalten
  trigger:
    - platform: time
      at: "06:00"
  condition:
    - condition: state
      entity_id: input_select.state_house
      state: 'Nacht'
    - condition: state
      entity_id: binary_sensor.workday_today
      state: 'on'
    - condition: state
      entity_id: input_boolean.holiday_mode
      state: 'off'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.state_house
        option: 'Bewohnt'

- alias: Haus an freien Tagen morgens einschalten
  trigger:
    - platform: time
      at: "08:00"
  condition:
    - condition: state
      entity_id: input_select.state_house
      state: 'Nacht'
    - condition: or
      conditions:
      - condition: state
        entity_id: binary_sensor.workday_today
        state: 'off'
      - condition: state
        entity_id: input_boolean.holiday_mode
        state: 'on'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.state_house
        option: 'Bewohnt'

- alias: Haus einschalten wenn jemand nach Hause kommt
  trigger:
  - platform: state
    entity_id: group.bewohner
    to: 'home'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.state_house
        option: 'Bewohnt'

- alias: Haus einschalten wenn jemand in einem Raum ist
  trigger:
    - platform: state
      entity_id: input_select.state_living_room
      to: 'On'
    - platform: state
      entity_id: input_select.state_living_room
      to: 'Bewohnt'
    - platform: state
      entity_id: input_select.state_front_hallway
      to: 'Bewohnt'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: input_select.state_house
        state: 'Leer'
      - condition: state
        entity_id: input_select.state_house
        state: 'Leerstehend'
      - condition: state
        entity_id: input_select.state_house
        state: 'Erwartend'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.state_house
        option: 'Bewohnt'

###############################################################################
### ==> Leer
###############################################################################

- alias: Haus ausschalten wenn niemand mehr zu Hause ist
  trigger:
  - platform: state
    entity_id: group.bewohner
    to: 'not_home'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.state_house
        option: 'Leer'

###############################################################################
### ==> Erwartend
###############################################################################

- alias: Haus auf erwartend schalten wenn Andrea die Arbeit verlässt
  trigger:
  - platform: zone
    entity_id: person.andrea
    zone: zone.work_andrea
    event: leave
  condition:
    - condition: state
      entity_id: input_select.state_house
      state: 'Leer'
    - condition: state
      entity_id: binary_sensor.workday_today
      state: 'on'
    - condition: state
      entity_id: input_boolean.holiday_mode
      state: 'off'
    - condition: time
      after: '15:00:00'
      before: '18:00:00'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.state_house
        option: 'Erwartend'

- alias: Haus auf erwartend schalten wenn Pascal die Arbeit verlässt
  trigger:
  - platform: zone
    entity_id: person.andrea
    zone: zone.work_pascal
    event: leave
  condition:
    - condition: state
      entity_id: input_select.state_house
      state: 'Leer'
    - condition: state
      entity_id: binary_sensor.workday_today
      state: 'on'
    - condition: state
      entity_id: input_boolean.holiday_mode
      state: 'off'
    - condition: time
      after: '16:00:00'
      before: '19:00:00'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.state_house
        option: 'Erwartend'

###############################################################################
### ==> Nacht
###############################################################################

- alias: Haus auf Nacht schalten, wenn der aktuelle Tag ein Werktag ist
  trigger:
    - platform: time
      at: "00:00:00"
  condition:
    - condition: state
      entity_id: binary_sensor.workday_today
      state: 'on'
    - condition: state
      entity_id: input_boolean.holiday_mode
      state: 'off'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.state_house
        option: 'Nacht'

- alias: Haus auf Nacht schalten, wenn der aktuelle Tag kein Werktag ist
  trigger:
    - platform: time
      at: "02:00:00"
  condition:
    - condition: or
      conditions:
      - condition: state
        entity_id: binary_sensor.workday_today
        state: 'off'
      - condition: state
        entity_id: input_boolean.holiday_mode
        state: 'on'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.state_house
        option: 'Nacht'

- id: house_state_set_night_with_button
  alias: Zustand Haus - Mit Button auf Nacht schalten
  trigger:
    - platform: event
      event_type: "deconz_event"
      event_data:
        device_id: "8e9305d9f10fe031de40d1a64e419fe0" #Tradfri Shortcut Button Goodnight
        event: 1002
  action:
    - alias: "Haus auf Nacht schalten"
      service: input_select.select_option
      data:
        entity_id: input_select.state_house
        option: 'Nacht'
    - alias: "Esszimmer ausschalten"
      service: script.state_dining_room_off
    - alias: "Küche ausschalten"
      service: script.state_kitchen_off
    - alias: "Wohnzimmer ausschalten"
      service: script.state_living_room_off