###############################################################################
### ==> An
###############################################################################

- alias: Kuechenzustand mit Remote auf An schalten
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: tradfri_switch_kitchen_1
        event: 1002
  condition:
    condition: or
    conditions:
    - condition: state
      entity_id: input_select.state_kitchen
      state: 'Bewohnt'
    - condition: state
      entity_id: input_select.state_kitchen
      state: 'Leer'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.state_kitchen
        option: 'An'

###############################################################################
### ==> Leer
###############################################################################

- alias: Kuechenzustand mit Remote auf Leer schalten
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: tradfri_switch_kitchen_1
        event: 1002
  condition:
    condition: state
    entity_id: input_select.state_kitchen
    state: 'An'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.state_kitchen
        option: 'Leer'

- alias: Küche auf Leer schalten wenn niemand dort ist
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_kitchen_1
      to: 'off'
  condition:
    condition: state
    entity_id: input_select.state_kitchen
    state: 'Bewohnt'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.state_kitchen
        option: 'Leer'

- alias: Küche - Timeout des Raums wenn er leer steht
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_kitchen_1
      to: 'off'
      for: '00:05:00'
  condition:
    condition: state
    entity_id: input_select.state_kitchen
    state: 'An'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.state_kitchen
        option: 'Leer'

###############################################################################
### ==> Bewohnt
###############################################################################

- alias: Küche auf Bewohnt schalten wenn jemand dort ist
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_kitchen_1
      to: 'on'
  condition:
    condition: state
    entity_id: input_select.state_kitchen
    state: 'Leer'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.state_kitchen
        option: 'Bewohnt'