###############################################################################
### ==> An
###############################################################################

- alias: Kuechenzustand mit Remote auf An schalten
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: tradfri_switch_kitchen_1
        event: 1002
  condition:
    condition: or
    conditions:
    - condition: state
      entity_id: input_select.state_kitchen
      state: 'Bewohnt'
    - condition: state
      entity_id: input_select.state_kitchen
      state: 'Leer'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.state_kitchen
        option: 'An'
    - service: script.sonos_say
      data:
        entity_id: media_player.kueche
        message: "Licht an"
        delay: 0
        volume: 0.3

###############################################################################
### ==> Leer
###############################################################################

- id: state_kitche_set_to_off_with_remote
  alias: Kuechenzustand mit Remote auf Leer schalten
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: tradfri_switch_kitchen_1
        event: 1002
  condition:
    - condition: state
      entity_id: input_select.state_kitchen
      state: 'An'
    - condition: state
      entity_id: binary_sensor.motion_kitchen_1
      state: 'off'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.state_kitchen
        option: 'Leer'
    - service: script.sonos_say
      data:
        entity_id: media_player.kueche
        message: "Licht aus"
        delay: 3
        volume: 0.3

- alias: K端che auf Leer schalten wenn niemand dort ist
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_kitchen_1
      to: 'off'
  condition:
    condition: state
    entity_id: input_select.state_kitchen
    state: 'Bewohnt'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.state_kitchen
        option: 'Leer'

- alias: K端che - Timeout des Raums wenn er leer steht
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_kitchen_1
      to: 'off'
      for: '00:05:00'
  condition:
    condition: state
    entity_id: input_select.state_kitchen
    state: 'An'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.state_kitchen
        option: 'Leer'

###############################################################################
### ==> Bewohnt
###############################################################################

- alias: K端che auf Bewohnt schalten wenn jemand dort ist
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_kitchen_1
      to: 'on'
  condition:
    condition: state
    entity_id: input_select.state_kitchen
    state: 'Leer'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.state_kitchen
        option: 'Bewohnt'

- id: state_kitchen_set_to_occupied_with_remote
  alias: K端che - Zustand mit Remote auf Bewohnt schalten
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: tradfri_switch_kitchen_1
        event: 1002
  condition:
    - condition: state
      entity_id: input_select.state_kitchen
      state: 'An'
    - condition: state
      entity_id: binary_sensor.motion_kitchen_1
      state: 'on'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.state_kitchen
        option: 'Bewohnt'
    - service: script.sonos_say
      data:
        entity_id: media_player.kueche
        message: "Licht aus"
        delay: 3
        volume: 0.3
