###############################################################################
### ==> An
###############################################################################

- alias: Wohnzimmerzustand mit Remote auf An schalten
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: tradfri_switch_wohnzimmer_1
        event: 1002
    - platform: event
      event_type: deconz_event
      event_data:
        id: tradfri_switch_wohnzimmer_2
        event: 1002
  condition:
    condition: or
    conditions:
    - condition: state
      entity_id: input_select.state_living_room
      state: 'Bewohnt'
    - condition: state
      entity_id: input_select.state_living_room
      state: 'Leer'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.state_living_room
        option: 'An'

- alias: Wohnzimmerzustand auf An und Gedämmt schalten wenn jemand dort ist und der Fernseher läuft
  trigger:
    - platform: state
      entity_id: binary_sensor.occupancy_living_room
      to: 'on'
  condition:
    - condition: state
      entity_id: input_select.state_living_room
      state: 'Leer'
    - condition: state
      entity_id: media_player.fernseher_wohnzimmer
      state: 'on'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.state_living_room
        option: 'An'
    - service: input_select.select_option
      data:
        entity_id: input_select.mode_living_room
        option: 'Gedaemmt'

###############################################################################
### ==> Leer
###############################################################################

- alias: Wohnzimmerzustand mit Remote auf Leer schalten
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: tradfri_switch_wohnzimmer_1
        event: 1002
    - platform: event
      event_type: deconz_event
      event_data:
        id: tradfri_switch_wohnzimmer_2
        event: 1002
  condition:
    - condition: state
      entity_id: input_select.state_living_room
      state: 'An'
    - condition: state
      entity_id: binary_sensor.occupancy_living_room
      state: 'off'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.state_living_room
        option: 'Leer'

- alias: Wohnzimmerzustand auf Leer schalten wenn niemand dort ist
  trigger:
    - platform: state
      entity_id: binary_sensor.occupancy_living_room
      to: 'off'
  condition:
    condition: state
    entity_id: input_select.state_living_room
    state: 'Bewohnt'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.state_living_room
        option: 'Leer'

###############################################################################
### ==> Bewohnt
###############################################################################

- alias: Wohnzimmerzustand auf Bewohnt schalten wenn jemand dort ist
  trigger:
    - platform: state
      entity_id: binary_sensor.occupancy_living_room
      to: 'on'
  condition:
    - condition: state
      entity_id: input_select.state_living_room
      state: 'Leer'
    - condition: state
      entity_id: media_player.fernseher_wohnzimmer
      state: 'off'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.state_living_room
        option: 'Bewohnt'

- alias: Wohnzimmerzustand mit Remote auf Leer schalten
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: tradfri_switch_wohnzimmer_1
        event: 1002
    - platform: event
      event_type: deconz_event
      event_data:
        id: tradfri_switch_wohnzimmer_2
        event: 1002
  condition:
    - condition: state
      entity_id: input_select.state_living_room
      state: 'An'
    - condition: state
      entity_id: binary_sensor.occupancy_living_room
      state: 'on'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.state_living_room
        option: 'Bewohnt'