###############################################################################
### Set thermostats according to house states
###############################################################################

- alias: Thermostate ausschalten, wenn das Haus den Zustand wechselt
  trigger:
  - platform: state
    entity_id: input_select.state_house
    to: 'Leer'
  - platform: state
    entity_id: input_select.state_house
    to: 'Nacht'
  - platform: state
    entity_id: input_select.state_house
    to: 'Leerstehend'
  action:
    - service: climate.set_preset_mode
      data:
        entity_id:
          - group.all_thermostats
        preset_mode: 'eco'

- alias: Thermostate einschalten, wenn das Haus den Zustand wechselt
  trigger:
  - platform: state
    entity_id: input_select.state_house
    to: 'Bewohnt'
  - platform: state
    entity_id: input_select.state_house
    to: 'Erwartend'
  condition:
    condition: time
    after: '05:00'
    before: '22:00'
  action:
    - service: climate.set_preset_mode
      data:
        entity_id:
          - group.all_thermostats
        preset_mode: 'comfort'

###############################################################################
### Switch living room thermostats according to balcony doors
###############################################################################

- id: thermostats_living_room_turn_off_balcony_open
  alias: "Wohnzimmer - Thermostate ausschalten wenn der Balkon offen ist"
  trigger:
    - platform: state
      entity_id: binary_sensor.living_room_balcony_door
      to: 'on'
      for: '00:02:00'
  action:
    - service: climate.turn_off
      data:
        entity_id: group.thermostats_living_room

- id: thermostats_living_room_turn_on_balcony_closed
  alias: "Wohnzimmer - Thermostate einschalten wenn der Balkon geschlossen ist"
  trigger:
    - platform: state
      entity_id: binary_sensor.living_room_balcony_door
      to: 'off'
  action:
    - service: climate.turn_on
      data:
        entity_id: group.thermostats_living_room
