- alias: Abendliche Wettervorhersage
  trigger:
    - platform: time
      at: "20:00:00"
  action:
    - service: notify.telegram_alle
      data_template:
        message: Heute Nacht werden es {{ states('sensor.weather_forecast_7_hours_temperature') }}°C. (Letztes Update {{ states.sensor.weather_forecast_7_hours_temperature.last_updated }}, letzte Änderung {{ states.sensor.weather_forecast_7_hours_temperature.last_changed }})