- alias: Pascal benachrichtigen wenn Andrea sich bewegt
  trigger:
    - platform: state
      entity_id: person.andrea
      to: not_home
  condition:
    - condition: state
      entity_id: person.pascal
      state:  home
  action:
    - service: homeassistant.update_entity
      entity_id: sensor.andrea_nach_hause
    - service: notify.telegram_pascal
      data_template:
        message: "Andrea hat {{ trigger.from_state.state }} verlassen und wird in ungefähr {{ states('sensor.andrea_nach_hause') }} Minuten zu Hause sein!"

- alias: Andrea benachrichtigen wenn Pascal sich bewegt
  trigger:
    - platform: state
      entity_id: person.pascal
      to: not_home
  condition:
    - condition: state
      entity_id: person.andrea
      state:  home
  action:
    - service: homeassistant.update_entity
      entity_id: sensor.pascal_nach_hause
    - service: notify.telegram_andrea
      data_template:
        message: "Pascal hat {{ trigger.from_state.state }} verlassen und wird in ungefähr {{ states('sensor.pascal_nach_hause') }} Minuten zu Hause sein!"