- alias: Benachrichtigung - Bei regnerischem Wetter Balkontür offen
  trigger:
  - platform: state
    entity_id: weather.home
    to: 'rainy'
  - platform: state
    entity_id: weather.home
    to: 'lightning-rainy'
  - platform: state
    entity_id: weather.home
    to: 'snowy'
  - platform: state
    entity_id: weather.home
    to: 'snowy-rainy'
  - platform: state
    entity_id: weather.home
    to: 'hail'
  condition:
    - condition: state
      entity_id: group.bewohner
      state: 'home'
    - condition: or
      conditions:
      - condition: state
        entity_id: binary_sensor.living_room_balcony_door
        state: 'on'
      - condition: state
        entity_id: binary_sensor.office_balcony_door
        state: 'on'
  action:
    - service: notify.telegram_alle
      data:
        message: "🌧 Bei dem Wetter wollt ihr vielleicht die Balkontüren schließen."
