- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /
    - type: memory_use_percent
    - type: processor_use

- platform: min_max
  name: Light living room
  type: max
  entity_ids:
    - sensor.light_living_room_1
    - sensor.light_living_room_2

- platform: template
  sensors:
    thermostat_bathroom_1_battery_level:
      friendly_name: "Batterie Thermostat Badezimmer"
      unit_of_measurement: '%'
      device_class: 'battery'
      value_template: "{{ state_attr('climate.badezimmer_1', 'battery_level') }}"

    living_room_temperature:
      friendly_name: "Temperatur Wohnzimmer"
      unit_of_measurement: "°C"
      value_template: "{{ state_attr('switch.outlet_living_room_2', 'temperature') }}"

    dining_room_temperature:
      friendly_name: "Temperatur Esszimmer"
      unit_of_measurement: "°C"
      value_template: "{{ state_attr('climate.thermostat_living_room_2', 'current_temperature') }}"

    temperature_outside:
      friendly_name: "Außentemperatur"
      unit_of_measurement: "°C"
      value_template: "{{ state_attr('weather.dwd', 'temperature') }}"

    ha_counter_lights:
      friendly_name: "Lichter"
      value_template: "{{ states.light | count}}"

    ha_counter_automations:
      friendly_name: "Automatisierungen"
      value_template: "{{ states.automation | count }}"

    ha_counter_sensors:
      friendly_name: "Sensoren"
      value_template: "{{ states.sensor | count + states.binary_sensor | count}}"

    ha_counter_switches:
      friendly_name: "Schalter"
      value_template: "{{ states.switch | count}}"

    phone_andrea_battery_level:
      friendly_name: "Akkustand Handy Andrea"
      value_template: "{{ state_attr('device_tracker.andrea_7dd6c1c6_c657_444c_ba6b_d3e3bc960423', 'battery_level')}}"

    phone_pascal_battery_level:
      friendly_name: "Akkustand Handy Pascal"
      value_template: "{{ state_attr('device_tracker.pascal_handy', 'battery_level')}}"

    occupancy_living_room_probability:
      friendly_name: ""
      value_template: "{{ state_attr('binary_sensor.occupancy_living_room', 'probability') * 100}}"

    occupancy_dining_room_probability:
      friendly_name: ""
      value_template: "{{ state_attr('binary_sensor.occupancy_dining_room', 'probability') * 100}}"
