- platform: yr
  name: Weather Forecast 1 Hours
  forecast: 1
  monitored_conditions:
    - temperature

- platform: yr
  name: Weather Forecast 2 Hours
  forecast: 2
  monitored_conditions:
    - temperature

- platform: yr
  name: Weather Forecast 3 Hours
  forecast: 3
  monitored_conditions:
    - temperature

- platform: yr
  name: Weather Forecast 4 Hours
  forecast: 4
  monitored_conditions:
    - temperature

- platform: yr
  name: Weather Forecast 5 Hours
  forecast: 5
  monitored_conditions:
    - temperature

- platform: yr
  name: Weather Forecast 6 Hours
  forecast: 6
  monitored_conditions:
    - temperature

- platform: yr
  name: Weather Forecast 7 Hours
  forecast: 7
  monitored_conditions:
    - temperature

- platform: yr
  name: Weather Forecast 8 Hours
  forecast: 8
  monitored_conditions:
    - temperature

- platform: yr
  name: Weather Forecast 9 Hours
  forecast: 9
  monitored_conditions:
    - temperature

- platform: yr
  name: Weather Forecast 10 Hours
  forecast: 10
  monitored_conditions:
    - temperature

- platform: yr
  name: Weather Forecast 11 Hours
  forecast: 11
  monitored_conditions:
    - temperature

- platform: yr
  name: Weather Forecast 12 Hours
  forecast: 12
  monitored_conditions:
    - temperature

- platform: min_max
  name: Minimal Temperature Forecast
  type: min
  entity_ids:
    - sensor.weather_forecast_1_hours_temperature
    - sensor.weather_forecast_2_hours_temperature
    - sensor.weather_forecast_3_hours_temperature
    - sensor.weather_forecast_4_hours_temperature
    - sensor.weather_forecast_5_hours_temperature
    - sensor.weather_forecast_6_hours_temperature
    - sensor.weather_forecast_7_hours_temperature
    - sensor.weather_forecast_8_hours_temperature
    - sensor.weather_forecast_9_hours_temperature
    - sensor.weather_forecast_10_hours_temperature
    - sensor.weather_forecast_11_hours_temperature
    - sensor.weather_forecast_12_hours_temperature