- alias: Sonos Esszimmer - Mit Küche verbinden
  trigger:
    - device_id: f4093bdae6d44f4e805e481c5c39bc1c #Tradfri Switch Dining Room 1
      domain: deconz
      platform: device
      type: remote_button_short_press
      subtype: right
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: media_player.esszimmer
          state: 'paused'
        - condition: state
          entity_id: media_player.esszimmer
          state: 'idle'
    - condition: state
      entity_id: media_player.kueche
      state: 'playing'
  action:
    - service: media_player.volume_set
      data:
        entity_id: media_player.kueche
        volume_level: 0.1
    - service: sonos.join
      data:
        entity_id: media_player.esszimmer
        master: media_player.kueche

- alias: Sonos Esszimmer - Duo Mix spielen
  trigger:
    - device_id: f4093bdae6d44f4e805e481c5c39bc1c #Tradfri Switch Dining Room 1
      domain: deconz
      platform: device
      type: remote_button_short_press
      subtype: right
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: media_player.esszimmer
          state: 'paused'
        - condition: state
          entity_id: media_player.esszimmer
          state: 'idle'
    - condition: or
      conditions:
        - condition: state
          entity_id: media_player.kueche
          state: 'paused'
        - condition: state
          entity_id: media_player.kueche
          state: 'idle'
  action:
    - service: sonos.unjoin
      data:
        entity_id: media_player.esszimmer
    - service: media_player.volume_set
      data:
        entity_id: media_player.kueche
        volume_level: 0.1
    - service: media_player.select_source
      data:
        entity_id: media_player.esszimmer
        source: Duo Mix

- alias: Sonos Esszimmer - Entkoppeln
  trigger:
    - device_id: f4093bdae6d44f4e805e481c5c39bc1c #Tradfri Switch Dining Room 1
      domain: deconz
      platform: device
      type: remote_button_short_press
      subtype: left
    - platform: state
      entity_id: media_player.fernseher_wohnzimmer
      to: 'on'
  action:
    - service: sonos.unjoin
      data:
        entity_id: media_player.esszimmer

- id: dining_room_reshuffle_sonos
  alias: "Esszimmer - Sonos neu shufflen"
  trigger:
    - platform: state
      entity_id: media_player.esszimmer
      to: 'paused'
      for: '00:10:00'
    - platform: state
      entity_id: media_player.esszimmer
      to: 'idle'
      for: '00:10:00'
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: media_player.kueche
          state: 'paused'
        - condition: state
          entity_id: media_player.kueche
          state: 'idle'
  action:
    service: script.reshuffle_media
    data:
      entity_id: media_player.esszimmer
