- alias: Sonos Esszimmer - Mit Küche verbinden
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: tradfri_switch_wohnzimmer_2
        event: 5002
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: media_player.esszimmer
          state: 'paused'
        - condition: state
          entity_id: media_player.esszimmer
          state: 'idle'
    - condition: state
      entity_id: media_player.kueche
      state: 'playing'
  action:
    - service: media_player.volume_set
      data:
        entity_id: media_player.kueche
        volume_level: 0.1
    - service: sonos.join
      data:
        entity_id: media_player.esszimmer
        master: media_player.kueche

- alias: Sonos Esszimmer - Family Mix spielen
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: tradfri_switch_wohnzimmer_2
        event: 5002
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: media_player.esszimmer
          state: 'paused'
        - condition: state
          entity_id: media_player.esszimmer
          state: 'idle'
    - condition: or
      conditions:
        - condition: state
          entity_id: media_player.kueche
          state: 'paused'
        - condition: state
          entity_id: media_player.kueche
          state: 'idle'
  action:
    - service: sonos.unjoin
      data:
        entity_id: media_player.esszimmer
    - service: media_player.volume_set
      data:
        entity_id: media_player.kueche
        volume_level: 0.1
    - service: media_player.select_source
      data:
        entity_id: media_player.esszimmer
        source: Family Mix

- alias: Sonos Esszimmer - Entkoppeln und pausieren
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: tradfri_switch_wohnzimmer_2
        event: 4002
    - platform: state
      entity_id: media_player.fernseher_wohnzimmer
      to: 'on'
  action:
    - service: sonos.unjoin
      data:
        entity_id: media_player.esszimmer
    - service: media_player.media_pause
      data:
        entity_id: media_player.esszimmer

- id: dining_room_reshuffle_sonos
  alias: "Esszimmer - Sonos neu shufflen"
  trigger:
    - platform: state
      entity_id: media_player.esszimmer
      to: 'paused'
      for: '00:10:00'
    - platform: state
      entity_id: media_player.esszimmer
      to: 'idle'
      for: '00:10:00'
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: media_player.kueche
          state: 'paused'
        - condition: state
          entity_id: media_player.kueche
          state: 'idle'
  action:
    service: script.reshuffle_media
    data:
      entity_id: media_player.esszimmer
