- alias: Sonos Küche - Mit Esszimmer verbinden
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: tradfri_switch_kitchen_1
        event: 5002
    - platform: state
      entity_id: input_select.state_kitchen
      to: 'An'
    - platform: state
      entity_id: input_select.state_kitchen
      to: 'Bewohnt'
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: media_player.kueche
          state: 'paused'
        - condition: state
          entity_id: media_player.kueche
          state: 'idle'
    - condition: state
      entity_id: media_player.esszimmer
      state: 'playing'
  action:
    - service: media_player.volume_set
      data:
        entity_id: media_player.kueche
        volume_level: 0.05
    - service: sonos.join
      data:
        entity_id: media_player.kueche
        master: media_player.esszimmer

- alias: Sonos Küche - Family Mix spielen
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: tradfri_switch_kitchen_1
        event: 5002
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: media_player.esszimmer
          state: 'paused'
        - condition: state
          entity_id: media_player.esszimmer
          state: 'idle'
    - condition: or
      conditions:
        - condition: state
          entity_id: media_player.kueche
          state: 'paused'
        - condition: state
          entity_id: media_player.kueche
          state: 'idle'
  action:
    - service: sonos.unjoin
      data:
        entity_id: media_player.kueche
    - service: media_player.volume_set
      data:
        entity_id: media_player.kueche
        volume_level: 0.05
    - service: media_player.select_source
      data:
        entity_id: media_player.kueche
        source: Family Mix

- alias: Sonos Küche - Entkoppeln und pausieren
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: tradfri_switch_kitchen_1
        event: 4002
    - platform: state
      entity_id: input_select.state_kitchen
      to: 'Leer'
      for: '00:03:00'
  action:
    - service: sonos.unjoin
      data:
        entity_id: media_player.kueche
    - service: media_player.media_pause
      data:
        entity_id: media_player.kueche