- alias: Sonos Küche - Mit Esszimmer verbinden
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: tradfri_switch_kitchen_1
        event: 5002
    - platform: state
      entity_id: input_select.state_kitchen
      to: 'An'
    - platform: state
      entity_id: input_select.state_kitchen
      to: 'Bewohnt'
  condition:
    - condition: state
      entity_id: media_player.kueche
      state: 'paused'
    - condition: state
      entity_id: media_player.esszimmer
      state: 'playing'
  action:
    - service: sonos.join
      data:
        entity_id: media_player.kueche
        master: media_player.esszimmer
    - service: media_player.volume_set
      data:
        entity_id: media_player.kueche
        volume_level: 0.1

- alias: Sonos Küche - Family Mix spielen
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: tradfri_switch_kitchen_1
        event: 5002
  condition:
    - condition: state
      entity_id: media_player.kueche
      state: 'paused'
    - condition: state
      entity_id: media_player.esszimmer
      state: 'paused'
  action:
    - service: sonos.unjoin
      data:
        entity_id: media_player.kueche
    - service: media_player.select_source
      data:
        entity_id: media_player.kueche
        source: Family Mix

- alias: Sonos Küche - Entkoppeln und pausieren
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: tradfri_switch_kitchen_1
        event: 4002
    - platform: state
      entity_id: input_select.state_kitchen
      to: 'Leer'
  action:
    - service: sonos.unjoin
      data:
        entity_id: media_player.kueche
    - service: media_player.media_pause
      data:
        entity_id: media_player.kueche