- alias: Frontlicht einschalten wenn der Bewegungssensor auslöst
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_front_door_1
      from: 'off'
      to: 'on'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: input_boolean.disable_occupation_lights
      state: 'off'
  action:
    - service: light.turn_on
      entity_id: light.front_door_1
      data:
        transition: 1
        brightness: 255

- alias: Frontlicht ausschalten wenn der Bewegungssensor nicht mehr auslöst
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_front_door_1
      from: 'on'
      to: 'off'
      for:
        seconds: 10
  action:
    - service: light.turn_off
      entity_id: light.front_door_1
      data:
        transition: 10