- alias: Kuechenlicht einschalten
  trigger:
    - platform: state
      entity_id: input_select.state_kitchen
      to: 'An'
    - platform: state
      entity_id: input_select.state_kitchen
      to: 'Bewohnt'
  action:
    - service: scene.turn_on
      entity_id: scene.kitchen_normal

- alias: Kuechenlicht ausschalten
  trigger:
    - platform: state
      entity_id: input_select.state_kitchen
      to: 'Leer'
  action:
    - service: scene.turn_on
      entity_id: scene.kitchen_off
