- alias: Kuechenlicht einschalten
  trigger:
    - platform: state
      entity_id: input_select.state_kitchen
      to: 'An'
  action:
    - service: light.turn_on
      data:
        brightness: 255
        transition: 1
        entity_id: light.kueche_decke

- alias: Küche automatisch beleuchten (Tag)
  trigger:
    - platform: state
      entity_id: input_select.state_kitchen
      to: 'Bewohnt'
  condition:
    - condition: state
      entity_id: input_select.state_house
      state: 'Bewohnt'
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
    - service: light.turn_on
      data:
        brightness: 255
        transition: 1
        entity_id: light.kueche_decke

- alias: Küche automatisch beleuchten (Nacht)
  trigger:
    - platform: state
      entity_id: input_select.state_kitchen
      to: 'Bewohnt'
  condition:
    - condition: state
      entity_id: input_select.state_house
      state: 'Nacht'
  action:
    - service: light.turn_on
      data:
        brightness: 50
        transition: 0.5
        entity_id: light.kueche_decke

- alias: Küche entleuchten
  trigger:
    - platform: state
      entity_id: input_select.state_kitchen
      to: 'Leer'
  action:
    - service: light.turn_off
      data:
        entity_id: light.kueche_decke
        transition: 1