- alias: Wohnzimmerlicht auf Normal schalten
  trigger:
    - platform: state
      entity_id: input_select.state_living_room
      to: 'An'
  action:
    - service: scene.turn_on
      entity_id: scene.wohnzimmer_normal

- alias: Wohnzimmerlicht auf Gedaemmt schalten
  trigger:
    - platform: state
      entity_id: input_select.state_living_room
      to: 'Gedaemmt'
    - platform: state
      entity_id: sun.sun
      to: 'below_horizon'
  condition:
    - condition: state
      entity_id: input_select.state_house
      state: 'Gedaemmt'
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
    - service: scene.turn_on
      entity_id: scene.wohnzimmer_gedaemmt

- alias: Wohnzimmerlicht ausschalten
  trigger:
    - platform: state
      entity_id: input_select.state_living_room
      to: 'Leer'
  action:
    - service: scene.turn_on
      entity_id: scene.wohnzimmer_aus

- alias: Wohnzimmerlicht Automatik
  trigger:
    - platform: state
      entity_id: input_select.state_living_room
      to: 'Bewohnt'
    - platform: state
      entity_id: sun.sun
      to: 'below_horizon'
  condition:
    - condition: state
      entity_id: input_select.state_living_room
      state: 'Bewohnt'
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: input_select.state_house
      state: 'Bewohnt'
  action:
    - service: scene.turn_on
      entity_id: scene.wohnzimmer_automatik

- alias: Wohnzimmerlicht Automatik Nachtlicht
  trigger:
    - platform: state
      entity_id: input_select.state_living_room
      to: 'Bewohnt'
  condition:
    - condition: state
      entity_id: input_select.state_house
      state: 'Nacht'
  action:
    - service: scene.turn_on
      entity_id: scene.wohnzimmer_nacht