# Modi durchwechseln
- alias: Wohnzimmermodus erhöhen (Remote 1)
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: tradfri_switch_wohnzimmer_1
        event: 3002
  condition:
    - condition: state
      entity_id: light.wohnzimmer_ventilator
      state: 'on'
  action:
    - service: input_select.select_next
      data:
        entity_id: input_select.mode_living_room

- alias: Wohnzimmermodus senken (Remote 1)
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: tradfri_switch_wohnzimmer_1
        event: 2002
  condition:
    - condition: state
      entity_id: light.wohnzimmer_ventilator
      state: 'on'
  action:
    - service: input_select.select_previous
      data:
        entity_id: input_select.mode_living_room

- alias: Wohnzimmermodus erhöhen (Remote 2)
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: tradfri_switch_wohnzimmer_2
        event: 3002
  condition:
    - condition: state
      entity_id: light.wohnzimmer_ventilator
      state: 'on'
  action:
    - service: input_select.select_next
      data:
        entity_id: input_select.mode_living_room

- alias: Wohnzimmermodus senken (Remote 2)
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: tradfri_switch_wohnzimmer_2
        event: 2002
  condition:
    - condition: state
      entity_id: light.wohnzimmer_ventilator
      state: 'on'
  action:
    - service: input_select.select_previous
      data:
        entity_id: input_select.mode_living_room

# Szenen abhängig vom Modus
- alias: Wohnzimmerlicht auf Komplett schalten
  trigger:
    platform: state
    entity_id: input_select.mode_living_room
    to: "Komplett"
  action:
    - service: scene.turn_on
      entity_id: scene.livingroom_full

- alias: Wohnzimmerlicht auf Normal schalten
  trigger:
    platform: state
    entity_id: input_select.mode_living_room
    to: "Normal"
  action:
    - service: scene.turn_on
      entity_id: scene.livingroom_normal

- alias: Wohnzimmerlicht auf Gedämmt schalten
  trigger:
    platform: state
    entity_id: input_select.mode_living_room
    to: "Gedämmt"
  action:
    - service: scene.turn_on
      entity_id: scene.livingroom_dim

# Ein- und ausschalten
- alias: Licht im Wohnzimmer einschalten (Remote 1)
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: tradfri_switch_wohnzimmer_1
        event: 1002
  condition:
    - condition: state
      entity_id: light.wohnzimmer_ventilator
      state: 'off'
  action:
    - service: light.turn_on
      data:
        entity_id: light.wohnzimmer_ventilator

- alias: Licht im Wohnzimmer ausschalten (Remote 1)
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: tradfri_switch_wohnzimmer_1
        event: 1002
  condition:
    - condition: state
      entity_id: light.wohnzimmer_ventilator
      state: 'on'
  action:
    - service: light.turn_off
      data:
        entity_id: light.wohnzimmer_ventilator

- alias: Licht im Wohnzimmer einschalten (Remote 2)
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: tradfri_switch_wohnzimmer_2
        event: 1002
  condition:
    - condition: state
      entity_id: light.wohnzimmer_ventilator
      state: 'off'
  action:
    - service: light.turn_on
      data:
        entity_id: light.wohnzimmer_ventilator

- alias: Licht im Wohnzimmer ausschalten (Remote 2)
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: tradfri_switch_wohnzimmer_2
        event: 1002
  condition:
    - condition: state
      entity_id: light.wohnzimmer_ventilator
      state: 'on'
  action:
    - service: light.turn_off
      data:
        entity_id: light.wohnzimmer_ventilator
