- alias: Fernseher abschalten wenn niemand zuhause ist
  trigger:
  - platform: state
    entity_id: group.bewohner
    from: Home
    to: Away
    for: 00:05:00
  condition:
    - condition: template
      value_template: "{{ not is_state('media_player.fernseher_wohnzimmer', 'off') }}"
  action:
    - service: media_player.turn_off
      data:
        entity_id: fernseher_wohnzimmer
    - service: notify.telegram_alle
      data:
        message: "Ich hab den Fernseher für euch ausgeschaltet. ✌️"
